version: '3.8'

services:
  psql:
    image: postgres:alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=m3u
      - POSTGRES_PASSWORD=asdrty68

  m3u-fastapi:
    image: abpdock/m3u-fastapi:rpi
    # restart: always
    volumes:
      # - ~/abp-m3u/populate-epg/wallet:/opt/oracle/instantclient_21_3/network/admin
      - ~/abp-m3u/fastapi:/app/app
      - ~/abp-m3u/files:/app/files
      - ~/abp-m3u/fastapi:/app/db
      - ~/.ssh:/secrets
      # - ~/.wallet:/opt/oracle/instantclient_21_3/network/admin
      # - ~/m3u_fastapi:/app/app
      # - ~/files:/app/files
      # - ~/db:/app/db
    ports:
      - "8000:8000"
    depends_on:
      - psql
    # environment:
    #   - MAX_WORKERS=2
    #   - GUNICORN_CMD_ARGS=--keyfile=/secrets/telegram.key --certfile=/secrets/telegram.pem
    env_file:
      - ~/abp-m3u/fastapi/.env
      # - ~/m3u_fastapi/.env

volumes:
  pg_data:
